- key:               spero-testnet
  name:              Sperocoin Testnet
  client:            sperocoin                             # API client name.
  server:            http://user:password@127.0.0.1:18332 # Public Sperocoin node endpoint.
  height:            1087160                               # Initial block number from which sync will be started.
  min_confirmations: 6                                    # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         https://chain.so/address/PEPSTEST/#{address}
    transaction:     https://chain.so/tx/PEPSTEST/#{txid}
  status:            active
